### ISSUE TITLE
im noob

### ISSUE THREAD

**Issue by ProBlacKirito** [PRO100KatYT/SaveTheWorldClaimer#20] opened 2022-09-15 08:56 UTC
Traceback (most recent call last):
  File "C:\Users\eaudi\Desktop\Script\SaveTheWorldClaimer-main\SaveTheWorldClaimer.py", line 491, in <module>
    main()
  File "C:\Users\eaudi\Desktop\Script\SaveTheWorldClaimer-main\SaveTheWorldClaimer.py", line 374, in main
    levelsList = [int(reqFORTLevelsCheck['fortitude']), int(reqFORTLevelsCheck['offense']), int(reqFORTLevelsCheck['resistance']), int(reqFORTLevelsCheck['technology'])]
KeyError: 'technology'

this is error

**Comment by bns34** [comment] 2022-09-15 09:54
What level are you for "technology" in STW?

**Comment by PRO100KatYT** [comment] 2022-09-15 17:58
I'll look into this crash sometime in the near future.
For the time being, check if you have the latest SaveTheWorldClaimer version downloaded.
If so, and the program still crashes, you can temporarily "fix" it by setting the Spend_Research_Points value in the config to false. This will make the prorgam skip the automatic research points spending, which caused this crash.

**Comment by PRO100KatYT** [comment] 2022-09-16 17:17
After a further investigation and some testing I most likely found the cause of this error. I assume your technology research level is 0. The program tried to get the technology level despite it not existing in your profile. This leads to program crashing. It will be fixed in a future update.

**Comment by ProBlacKirito** [comment] 2022-09-16 17:56
How do I see this thing, do I have to install fortnite, open save the world, then? (Google translate)

**Comment by ProBlacKirito** [comment] 2022-09-16 18:12
raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='account-public-service-prod.ol.epicgames.com', port=443): Max retries exceeded with url:
 /account/api/oauth/token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

why?

**Comment by bns34** [comment] 2022-09-16 18:14
> How do I see this thing, do I have to install fortnite, open save the world, then? (Google translate)

If you want to see your research levels, then yes.

**Comment by PRO100KatYT** [comment] 2022-09-17 14:58
> Traceback (most recent call last): File "C:\Users\eaudi\Desktop\Script\SaveTheWorldClaimer-main\SaveTheWorldClaimer.py", line 491, in main() File "C:\Users\eaudi\Desktop\Script\SaveTheWorldClaimer-main\SaveTheWorldClaimer.py", line 374, in main levelsList = [int(reqFORTLevelsCheck['fortitude']), int(reqFORTLevelsCheck['offense']), int(reqFORTLevelsCheck['resistance']), int(reqFORTLevelsCheck['technology'])] KeyError: 'technology'
> 
> this is error

Fixed in the 1.10.1 update.

**Closed as completed by PRO100KatYT** 2022-09-17 14:58 UTC

**Comment by ProBlacKirito** [comment] 2022-09-17 15:58
raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='account-public-service-prod.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by ProxyError('Cannot connect
 to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
15:54 ~/SaveTheWorldClaimer $ 
![msg141781881-15517](https://user-images.githubusercontent.com/74011684/190865717-5f259b1d-a82e-4a9e-80a8-318888c6e7ea.jpg)





i update, but not work

**Comment by Playeereq** [comment] 2022-09-17 18:08
os?
